import { StyleSheet } from 'react-native';

export const shared = StyleSheet.create({
  background: {
    flex: 1,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  logoCard: {
    width: 180,
    height: 180,
    borderRadius: 40,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
  },
  logoImage: {
    width: 140,
    height: 140,
    borderRadius: 30,
  },
  button: {
    width: '100%',
    borderRadius: 26,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  buttonGradient: {
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '600',
  },
  decorCircleTop: {
    position: 'absolute',
    top: -80,
    left: -60,
    width: 320,
    height: 320,
    borderTopLeftRadius: 210,
    borderTopRightRadius: 130,
    borderBottomLeftRadius: 240,
    borderBottomRightRadius: 290,
    backgroundColor: 'rgba(255, 214, 64, 0.36)',
    borderWidth: 3,
    borderColor: '#4ec5fc81',
  },
  decorCircleBottom: {
    position: 'absolute',
    bottom: -100,
    right: -80,
    width: 280,
    height: 280,
    borderTopLeftRadius: 180,
    borderTopRightRadius: 260,
    borderBottomLeftRadius: 150,
    borderBottomRightRadius: 220,
    backgroundColor: 'rgba(79, 195, 232, 0.25)',
    borderWidth: 3,
    borderColor: '#FFD64080',
  },
  title: {
  fontFamily: 'Fredoka_700Bold',
  fontSize: 32,
  color: '#fff',
  marginBottom: 20,
  textAlign: 'center',
},
backButton: {
  position: 'absolute',
  top: 50,
  left: 20,
  width: 42,
  height: 42,
  borderRadius: 21,
  backgroundColor: 'rgba(255,255,255,0.25)',
  justifyContent: 'center',
  alignItems: 'center',
  zIndex: 10,
},

});